# Generated by Django 4.2.30 on 2026-04-11 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
