# Generated by Django 5.2.14 on 2026-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
